name: Build Firefox Plugin

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Firefox plugin
      run: |
        npm install
        npm run-script build:firefox:prod
    - name: Upload Firefox plugin
      uses: actions/upload-artifact@v2
      with:
        name: startupLink-chrome
        path: addon_firefox/addon_firefox.zip
