name: Build Chrome Plugin
# This workflow is triggered on pushes to the repository.
on:
  push:
    types:
    branches:
    - master         # Push events on master branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Chrome plugin
      run: |
        npm install
        npm run-script build:chrome:prod
        sudo apt install zip
        zip startupLink-chrome.zip addon/
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: startupLink-chrome.zip
          path: startupLink-chrome.zip
